const fs = require('fs');
const path = require('path');

const rootConfigPath = path.join(__dirname, 'config.json');

if (!fs.existsSync(rootConfigPath)) {
  console.error(`Error: config.json is required but does not exist at ${rootConfigPath}`);
  process.exit(1);
}

let config;
try {
  config = JSON.parse(fs.readFileSync(rootConfigPath, 'utf8'));
} catch (err) {
  console.error("Error: config.json is not valid JSON:", err.message);
  process.exit(1);
}

// Validate required fields
const requiredKeys = ['CDN_BASE_URL', 'API_BASE_URL', 'ENABLE_SIMULATION_DEBUG'];
for (const key of requiredKeys) {
  if (config[key] === undefined) {
    console.error(`Error: Missing required configuration key "${key}" in config.json`);
    process.exit(1);
  }
}

const cdnUrl = config.CDN_BASE_URL;
const apiUrl = config.API_BASE_URL;
const enableSimulationDebug = config.ENABLE_SIMULATION_DEBUG;

function writeSync(filePath, content) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

// 1. Sync to landing-page (JavaScript config object + constants)
const landingPageJsPath = path.join(__dirname, 'apps', 'landing-page', 'config.js');
const landingPageJsContent = `// Generated by sync_config.js. Do not edit manually.
const CONFIG = {
  CDN_BASE_URL: "${cdnUrl}",
  API_BASE_URL: "${apiUrl}",
  ENABLE_SIMULATION_DEBUG: ${enableSimulationDebug}
};

// Global variables for ease of use
const CDN_BASE_URL = CONFIG.CDN_BASE_URL;
const API_BASE_URL = CONFIG.API_BASE_URL;
const ENABLE_SIMULATION_DEBUG = CONFIG.ENABLE_SIMULATION_DEBUG;
`;
writeSync(landingPageJsPath, landingPageJsContent);
console.log(`Synced general config to landing-page: ${landingPageJsPath}`);

// 2. Sync to mobile (Dart Class)
const mobileDartPath = path.join(__dirname, 'apps', 'mobile', 'lib', 'core', 'config', 'app_config.dart');
const mobileDartContent = `// Generated by sync_config.js. Do not edit manually.
class AppConfig {
  static const String cdnBaseUrl = '${cdnUrl}';
  static const String apiBaseUrl = '${apiUrl}';
  static const bool enableSimulationDebug = ${enableSimulationDebug};
}
`;
writeSync(mobileDartPath, mobileDartContent);
console.log(`Synced general config to mobile: ${mobileDartPath}`);

// 3. Sync to web (Next.js JSON config)
const webConfigPath = path.join(__dirname, 'apps', 'web', 'src', 'app_config.json');
writeSync(webConfigPath, JSON.stringify(config, null, 2));
console.log(`Synced general config to web: ${webConfigPath}`);

// 4. Sync to backend (NestJS JSON config)
const backendConfigPath = path.join(__dirname, 'apps', 'backend', 'src', 'app_config.json');
writeSync(backendConfigPath, JSON.stringify(config, null, 2));
console.log(`Synced general config to backend: ${backendConfigPath}`);
