const fs = require('fs');
const path = require('path');
const https = require('https');
const http = require('http');

const rootConfigPath = path.join(__dirname, 'config.json');

if (!fs.existsSync(rootConfigPath)) {
  console.error(`Error: config.json is required but does not exist at ${rootConfigPath}`);
  process.exit(1);
}

let config;
try {
  config = JSON.parse(fs.readFileSync(rootConfigPath, 'utf8'));
} catch (err) {
  console.error("Error: config.json is not valid JSON:", err.message);
  process.exit(1);
}

// Override using environment variables if present (useful for CI/CD)
if (process.env.API_BASE_URL) {
  console.log(`Overriding API_BASE_URL with environment variable: ${process.env.API_BASE_URL}`);
  config.API_BASE_URL = process.env.API_BASE_URL;
}
if (process.env.CDN_BASE_URL) {
  console.log(`Overriding CDN_BASE_URL with environment variable: ${process.env.CDN_BASE_URL}`);
  config.CDN_BASE_URL = process.env.CDN_BASE_URL;
}
if (process.env.ENABLE_SIMULATION_DEBUG !== undefined) {
  const isTrue = process.env.ENABLE_SIMULATION_DEBUG === 'true';
  console.log(`Overriding ENABLE_SIMULATION_DEBUG with environment variable: ${isTrue}`);
  config.ENABLE_SIMULATION_DEBUG = isTrue;
}

// Validate required fields
const requiredKeys = ['CDN_BASE_URL', 'API_BASE_URL', 'ENABLE_SIMULATION_DEBUG'];
for (const key of requiredKeys) {
  if (config[key] === undefined) {
    console.error(`Error: Missing required configuration key "${key}" in config.json`);
    process.exit(1);
  }
}

const cdnUrl = config.CDN_BASE_URL;
const apiUrl = config.API_BASE_URL;
const enableSimulationDebug = config.ENABLE_SIMULATION_DEBUG;

function writeSync(filePath, content) {
  const dir = path.dirname(filePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

function downloadFile(url, destPath) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, (response) => {
      if (response.statusCode === 200) {
        const file = fs.createWriteStream(destPath);
        response.pipe(file);
        file.on('finish', () => {
          file.close();
          console.log(`Successfully downloaded branding asset from ${url} to ${destPath}`);
          resolve(true);
        });
      } else {
        reject(new Error(`Failed to download ${url}: ${response.statusCode} ${response.statusMessage}`));
      }
    }).on('error', (err) => {
      reject(err);
    });
  });
}

async function main() {
  // 0. Dynamic app name and branding overrides (tenant-specific)
  if (process.env.APP_NAME) {
    const appName = process.env.APP_NAME;
    console.log(`Overriding application display name to: ${appName}`);

    // Update Android Manifest
    const androidManifestPath = path.join(__dirname, 'apps', 'mobile', 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
    if (fs.existsSync(androidManifestPath)) {
      let content = fs.readFileSync(androidManifestPath, 'utf8');
      content = content.replace(/android:label="[^"]+"/, `android:label="${appName}"`);
      fs.writeFileSync(androidManifestPath, content, 'utf8');
      console.log(`Updated Android app label in Manifest.`);
    }

    // Update iOS Info.plist
    const iosPlistPath = path.join(__dirname, 'apps', 'mobile', 'ios', 'Runner', 'Info.plist');
    if (fs.existsSync(iosPlistPath)) {
      let content = fs.readFileSync(iosPlistPath, 'utf8');
      content = content.replace(/(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]+(<\/string>)/, `$1${appName}$2`);
      content = content.replace(/(<key>CFBundleName<\/key>\s*<string>)[^<]+(<\/string>)/, `$1${appName}$2`);
      fs.writeFileSync(iosPlistPath, content, 'utf8');
      console.log(`Updated iOS app display name and bundle name in Info.plist.`);
    }
  }

  // Dynamic asset downloads if CDN_BASE_URL is a remote HTTP endpoint
  if (cdnUrl.startsWith('http://') || cdnUrl.startsWith('https://')) {
    const logoUrl = `${cdnUrl.replace(/\/$/, '')}/logo.png`;
    const localLogoPath = path.join(__dirname, 'apps', 'mobile', 'assets', 'images', 'logo.png');
    
    console.log(`Attempting to download tenant logo from: ${logoUrl}`);
    try {
      await downloadFile(logoUrl, localLogoPath);
    } catch (err) {
      console.warn(`Warning: Could not download logo from CDN (${err.message}). Keeping default logo asset.`);
    }
  }

  // 1. Sync to landing-page (JavaScript config object + constants)
  const landingPageJsPath = path.join(__dirname, 'apps', 'landing-page', 'config.js');
  const landingPageJsContent = `// Generated by sync_config.js. Do not edit manually.
const CONFIG = {
  CDN_BASE_URL: "${cdnUrl}",
  API_BASE_URL: "${apiUrl}",
  ENABLE_SIMULATION_DEBUG: ${enableSimulationDebug}
};

// Global variables for ease of use
const CDN_BASE_URL = CONFIG.CDN_BASE_URL;
const API_BASE_URL = CONFIG.API_BASE_URL;
const ENABLE_SIMULATION_DEBUG = CONFIG.ENABLE_SIMULATION_DEBUG;
`;
  writeSync(landingPageJsPath, landingPageJsContent);
  console.log(`Synced general config to landing-page: ${landingPageJsPath}`);

  // 2. Sync to mobile (Dart Class)
  const mobileDartPath = path.join(__dirname, 'apps', 'mobile', 'lib', 'core', 'config', 'app_config.dart');
  const mobileDartContent = `// Generated by sync_config.js. Do not edit manually.
class AppConfig {
  static const String cdnBaseUrl = '${cdnUrl}';
  static const String apiBaseUrl = '${apiUrl}';
  static const bool enableSimulationDebug = ${enableSimulationDebug};
}
`;
  writeSync(mobileDartPath, mobileDartContent);
  console.log(`Synced general config to mobile: ${mobileDartPath}`);

  // 3. Sync to web (Next.js JSON config)
  const webConfigPath = path.join(__dirname, 'apps', 'web', 'src', 'app_config.json');
  writeSync(webConfigPath, JSON.stringify(config, null, 2));
  console.log(`Synced general config to web: ${webConfigPath}`);

  // 4. Sync to backend (NestJS JSON config)
  const backendConfigPath = path.join(__dirname, 'apps', 'backend', 'src', 'app_config.json');
  writeSync(backendConfigPath, JSON.stringify(config, null, 2));
  console.log(`Synced general config to backend: ${backendConfigPath}`);
}

main().catch((err) => {
  console.error("Fatal Error during configuration sync:", err);
  process.exit(1);
});
