// Generated by sync_config.js. Do not edit manually.
class AppConfig {
  static const String cdnBaseUrl = 'https://raw.githubusercontent.com/samuelj90/qrims/master';
  static const String apiBaseUrl = 'http://localhost:3000/api/v1';
  static const bool enableSimulationDebug = false;
}
