// Generated by sync_config.js. Do not edit manually.
const CONFIG = {
  CDN_BASE_URL: "https://raw.githubusercontent.com/samuelj90/qrims/master",
  API_BASE_URL: "http://localhost:3000/api/v1"
};

// Global variables for ease of use
const CDN_BASE_URL = CONFIG.CDN_BASE_URL;
const API_BASE_URL = CONFIG.API_BASE_URL;
